name: Release

on:
  push:
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CF_API_KEY: ${{ secrets.CF_API_KEY }}
      CF_URL: https://www.curseforge.com/wow/addons/elvui-ratiominimapauras
      WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
    steps:
      - name: Clone Project
        uses: actions/checkout@v3
        with:
          fetch-depth: 100
      - name: Setup Environment
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Release Job
        uses: BigWigsMods/packager@master
  notify-discord:
    env:
      WAGO_URL: https://addons.wago.io/addons/elvui-ratiominimapauras
    runs-on: ubuntu-latest
    if: ${{ success() }}
    needs: [release]
    steps:
      - uses: actions/checkout@v3
      - name: Notify Discord
        uses: repooc/djs-actions@my_changes
        with:
          id: ${{ secrets.DISCORD_WEBHOOK_ID }}
          token: ${{ secrets.DISCORD_WEBHOOK_TOKEN }}
          title: 'New *ElvUI_RatioMinimapAuras* Version Released!'
          description: '[Repooc](https://github.com/repooc) has released a new version of ElvUI_RatioMinimapAuras!

            If you use a wow addon client that can download from either wago addons or curse, then it is recommended that you use that to install/update the addon.  You can update how you see fit, even if you want to download manually and install it, go for it.  The can grab the addon from the links down below.'
          fields: '[{"name": "Released By:", "value": "[Repooc](https://github.com/repooc)", "inline": true}, {"name": "Issue Tracker:", "value": "[ElvUI_RatioMinimapAuras](https://github.com/repooc/ElvUI_RatioMinimapAuras/issues)", "inline": true}, {"name": "Version", "value": "Test", "inline": true}, {"name": "Wago Addons", "value": "[Click Here](${{ env.WAGO_URL }})", "inline": true}, {"name": "Curseforge", "value": "[Click Here](${{ env.CF_URL }})", "inline": true}]'
          footer: Addons by Repooc
          timestamp: true
